import {defineConfig} from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import {VitePWA} from 'vite-plugin-pwa';
import {resolve} from 'node:path';
import {tenantDevPlugin} from './scripts/vite/tenant-dev-plugin.ts';

// One shared JS/CSS build for every studio. The two HTML templates in shell/
// are rendered per tenant by scripts/tenant/render-site.ts after the build.
export default defineConfig({
  resolve: {
    alias: {
      '@': resolve(import.meta.dirname, 'src'),
      '@shared': resolve(import.meta.dirname, 'supabase/functions/_shared/core'),
    },
  },
  plugins: [
    react(),
    tailwindcss(),
    tenantDevPlugin(resolve(import.meta.dirname, '.generated/site')),
    VitePWA({
      strategies: 'injectManifest',
      srcDir: 'src/sw',
      filename: 'sw.ts',
      injectRegister: false,
      manifest: false, // per-tenant manifests are generated by the tenant pipeline
      injectManifest: {
        rollupFormat: 'iife',
        globPatterns: ['assets/**/*.{js,css,woff2}'],
        // Inter ships many unicode-range subsets; precache only what ru-RU UI uses.
        globIgnores: ['**/*greek*', '**/*vietnamese*'],
        maximumFileSizeToCacheInBytes: 3 * 1024 * 1024,
      },
      devOptions: {enabled: false},
    }),
  ],
  build: {
    target: 'es2022',
    sourcemap: true,
    rolldownOptions: {
      input: {
        client: resolve(import.meta.dirname, 'shell/client.html'),
        owner: resolve(import.meta.dirname, 'shell/owner.html'),
      },
    },
  },
  server: {
    port: 5173,
    strictPort: true,
    headers: {'Service-Worker-Allowed': '/s/'},
  },
  preview: {
    headers: {'Service-Worker-Allowed': '/s/'},
  },
});
