#!/usr/bin/env tsx
// Post-build step: turns the shared Vite build into a multi-tenant static site.
//   dist/s/<slug>/index.html         client shell (deep links rewrite here)
//   dist/s/<slug>/owner/index.html   owner shell
//   dist/t/<slug>/...                icons, splash, media, manifests
//   dist/_redirects, dist/_headers   Cloudflare Pages routing and headers
// Every tenant folder in tenants/ is rendered, so publishing a new studio never
// replaces an existing one.
import {mkdirSync, writeFileSync, rmSync, existsSync} from 'node:fs';
import {join, resolve} from 'node:path';
import {parseArgs} from 'node:util';
import {loadEnv} from 'vite';
import {listTenantSlugs, loadTenantOrThrow, ROOT} from './lib/load.ts';
import {generateTenantAssets, readTemplate} from './lib/assets.ts';
import {renderShell} from './lib/shell.ts';
import {configHash} from './lib/payload.ts';
import {isMain} from '../lib/is-main.ts';

export const REDIRECTS = `# Generated by scripts/tenant/render-site.ts
/s/:slug/owner/* /s/:slug/owner/index.html 200
/s/:slug/* /s/:slug/index.html 200
`;

/** Origins the browser may call: Supabase (Auth, Storage) and the Edge Functions. */
export function apiOrigins(vars: Record<string, string | undefined> = process.env): string[] {
  const origins = new Set<string>();
  for (const key of ['VITE_SUPABASE_URL', 'VITE_FUNCTIONS_URL', 'VITE_STORAGE_PUBLIC_URL']) {
    const value = vars[key];
    if (value && /^https?:\/\//.test(value)) origins.add(new URL(value).origin);
  }
  return [...origins];
}

export function headersFile(origins: string[]) {
  const remote = origins.length ? origins.join(' ') : 'https://*.supabase.co';
  const csp = [
    "default-src 'self'",
    `connect-src 'self' ${remote}`,
    `img-src 'self' data: blob: ${remote}`,
    "style-src 'self' 'unsafe-inline'",
    "script-src 'self'",
    "font-src 'self'",
    "worker-src 'self'",
    "manifest-src 'self'",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
  ].join('; ');
  return `# Generated by scripts/tenant/render-site.ts
/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), geolocation=(), microphone=()
  Content-Security-Policy: ${csp}

/sw.js
  Service-Worker-Allowed: /s/
  Cache-Control: no-cache

/s/*
  Cache-Control: no-cache

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/t/*
  Cache-Control: public, max-age=3600
`;
}

export async function renderSite(outDir: string, only?: string[], mode = 'production') {
  const slugs = only?.length ? only : listTenantSlugs();
  const client = readTemplate(outDir, 'client');
  const owner = readTemplate(outDir, 'owner');
  const rendered: string[] = [];
  for (const slug of slugs) {
    const cfg = loadTenantOrThrow(slug);
    const version = configHash(cfg);
    await generateTenantAssets(cfg, outDir, version);
    mkdirSync(join(outDir, 's', slug, 'owner'), {recursive: true});
    writeFileSync(join(outDir, 's', slug, 'index.html'), renderShell(client, cfg, 'client', version));
    writeFileSync(join(outDir, 's', slug, 'owner', 'index.html'), renderShell(owner, cfg, 'owner', version));
    rendered.push(slug);
  }
  writeFileSync(join(outDir, '_redirects'), REDIRECTS);
  // Same VITE_* values Vite embedded into the bundle (.env files + process env).
  writeFileSync(join(outDir, '_headers'), headersFile(apiOrigins(loadEnv(mode, ROOT, 'VITE_'))));
  writeFileSync(
    join(outDir, 'index.html'),
    `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Онлайн-запись</title><meta name="robots" content="noindex"><style>body{font:16px system-ui;background:#0b0c0e;color:#e8e8ea;display:grid;place-items:center;min-height:100vh;margin:0}</style></head><body><p>Откройте ссылку вашей студии вида <code>/s/&lt;studio&gt;/</code>.</p></body></html>`,
  );
  return rendered;
}

if (isMain(import.meta.url)) {
  const {values} = parseArgs({options: {out: {type: 'string', default: 'dist'}, mode: {type: 'string', default: 'production'}, only: {type: 'string', multiple: true}, keep: {type: 'boolean', default: false}}});
  const outDir = resolve(ROOT, values.out!);
  const done = await renderSite(outDir, values.only, values.mode);
  if (!values.keep && existsSync(join(outDir, 'shell'))) rmSync(join(outDir, 'shell'), {recursive: true});
  console.log(`rendered ${done.length} tenant(s): ${done.join(', ')}`);
}
