#!/usr/bin/env tsx
// Generates supabase/seed.sql from tenants/*/business.json:
//   * publishes every studio (preview mode),
//   * adds clearly marked demo bookings (source 'demo', is_demo = true) placed
//     relative to the day the seed runs, so they are always in the future,
//   * a few completed demo orders and payments for the statistics screen.
// Demo data never produces notifications (preview + is_demo => suppressed).
import {writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {listTenantSlugs, loadTenantOrThrow, ROOT} from './lib/load.ts';
import {imageMeta} from './lib/assets.ts';
import {buildPublishPayload, configHash} from './lib/payload.ts';
import {isMain} from '../lib/is-main.ts';

const DEMO_CLIENTS = [
  ['Алексей (демо)', '+70000000101', 'Toyota Camry', 'А101АА'],
  ['Марина (демо)', '+70000000102', 'BMW X5', 'В202ВВ'],
  ['Игорь (демо)', '+70000000103', 'Kia Rio', 'Е303ЕЕ'],
  ['Светлана (демо)', '+70000000104', 'Mercedes E', 'К404КК'],
  ['Дмитрий (демо)', '+70000000105', 'Skoda Octavia', 'М505ММ'],
] as const;

const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;

export async function generateSeed(): Promise<string> {
  const parts: string[] = [
    '-- GENERATED by `npm run seed:generate` from tenants/*/business.json. Do not edit by hand.',
    '-- Demo data only: every booking below is source = demo / is_demo = true and',
    '-- studios stay in preview, so no real notification is ever sent for it.',
    'set check_function_bodies = off;',
    '',
  ];
  for (const slug of listTenantSlugs()) {
    const cfg = loadTenantOrThrow(slug);
    const payload = buildPublishPayload(cfg, await imageMeta(cfg));
    parts.push(`-- ${slug}`);
    parts.push(`select app.publish_tenant(${lit(JSON.stringify(payload))}::jsonb, ${lit(configHash(cfg))});`);
    const services = cfg.services.filter((s) => s.completion === 'same_day').map((s) => s.key);
    const multi = cfg.services.find((s) => s.completion === 'multi_day')?.key;
    // Future demo bookings: nth free reception moment of the service.
    const future = services.slice(0, 4).map((key, i) => ({key, offset: 2 + i * 3, client: DEMO_CLIENTS[i % DEMO_CLIENTS.length]!}));
    if (multi) future.push({key: multi, offset: 1, client: DEMO_CLIENTS[4]!});
    for (const [i, b] of future.entries()) {
      parts.push(`select app.create_booking(t.id, s.id, a.start_at, ${lit(b.client[0])}, ${lit(b.client[1])}, ${lit(b.client[2])}, ${lit(b.client[3])},
  'Демо-запись', md5(${lit(`${slug}:future:${i}`)})::uuid, 'seed', null, 'demo', null, null, false)
from app.tenants t
join app.services s on s.tenant_id = t.id and s.key = ${lit(b.key)}
cross join lateral (
  select start_at from app.available_starts(t.id, s.id, (now() at time zone t.timezone)::date + 1, (now() at time zone t.timezone)::date + 20, null, true)
   where cardinality(free_resources) > 0 order by start_at offset ${b.offset} limit 1) a
where t.slug = ${lit(slug)};`);
    }
    // Two past demo orders (completed today) with payments, for the stats screen.
    for (const [i, key] of services.slice(0, 2).entries()) {
      const c = DEMO_CLIENTS[(i + 2) % DEMO_CLIENTS.length]!;
      parts.push(`with b as (
  select app.create_booking(t.id, s.id, a.start_at, ${lit(c[0])}, ${lit(c[1])}, ${lit(c[2])}, ${lit(c[3])},
    'Демо: выполнено', md5(${lit(`${slug}:past:${i}`)})::uuid, 'seed', null, 'demo', null, null, false) as r, t.id as tenant_id
  from app.tenants t
  join app.services s on s.tenant_id = t.id and s.key = ${lit(key)}
  cross join lateral (
    select start_at from app.available_starts(t.id, s.id, (now() at time zone t.timezone)::date - 3, (now() at time zone t.timezone)::date - 1, null, false)
     where cardinality(free_resources) > 0 order by start_at offset ${2 + i * 2} limit 1) a
  where t.slug = ${lit(slug)}
), done as (
  select tenant_id, (r -> 'booking' ->> 'id')::uuid as id, (r -> 'booking' -> 'price' ->> 'amount')::numeric as amount,
         app.set_booking_status(tenant_id, (r -> 'booking' ->> 'id')::uuid, 'completed', null, null) from b
)
select app.record_payment(tenant_id, id, amount, ${i ? "'card'" : "'cash'"}, now(), 'Демо-оплата',
  md5(${lit(`${slug}:pay:${i}`)})::uuid, null) from done;`);
    }
    parts.push('');
  }
  return parts.join('\n') + '\n';
}

if (isMain(import.meta.url)) {
  const sql = await generateSeed();
  writeFileSync(join(ROOT, 'supabase', 'seed.sql'), sql);
  console.log(`supabase/seed.sql: ${sql.length} bytes`);
}
